# Generated by Django 2.1.5 on 2019-08-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='layout',
            field=models.CharField(default='bbbbbbbbbbbb        wwwwwwwwwwww', max_length=64),
        ),
    ]
