# Generated by Django 2.1.5 on 2019-09-13 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20190813_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_sq', models.IntegerField()),
                ('to_sq', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='move',
            name='game',
        ),
        migrations.AddField(
            model_name='jump',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Turn'),
        ),
        migrations.AddField(
            model_name='move',
            name='turn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Turn'),
            preserve_default=False,
        ),
    ]
