# Generated by Django 2.1.5 on 2019-09-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190913_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jump',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
