# Generated by Django 2.2.6 on 2019-10-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    def create_random_AI(apps, schema_editor):
        User = apps.get_model('auth', 'User')
        u = User.objects.create(username='random_ai', first_name='Random', last_name='AI')
        u.save()

    dependencies = [
        ('api', '0005_game_winner'),
    ]

    operations = [
        migrations.RunPython(create_random_AI),
    ]
