export const BOARD_REQUESTED = "BOARD_REQUESTED"
export const BOARD_RECEIVE_SUCCESS = "BOARD_RECEIVE_SUCCESS"
export const BOARD_RECEIVE_FAILURE = "BOARD_RECEIVE_FAILURE"

export const SET_GAME_ID = "SET_GAME_ID"
export const SET_ACTIVE_SQUARE = "SET_ACTIVE_SQUARE"
export const MOVE_REQUESTED = "MOVE_REQUESTED"
export const MOVE_REQUEST_SUCCESS = "MOVE_REQUEST_SUCCESS"
export const MOVE_REQUEST_FAILURE = "MOVE_REQUEST_FAILURE"

export const JUMP_REQUESTED = "JUMP_REQUESTED"
export const JUMP_REQUEST_SUCCESS = "JUMP_REQUEST_SUCCESS"
export const JUMP_REQUEST_FAILURE = "JUMP_REQUEST_FAILURE"

export const USER_LIST_REQUESTED = "USER_LIST_REQUESTED"
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS"
export const USER_LIST_FAILURE = "USER_LIST_FAILURE"

export const TOGGLE_DEBUG_SYMBOLS = "TOGGLE_DEBUG_SYMBOLS"
